server:
  port: 8083
  servlet:
    session:
      timeout: 3600s
spring:
  application:
    name: redis-single
  redis:
    host: localhost
    port: 6379
    password: laod
    lettuce:
      pool:
        max-active: 8 #最大活跃连接数
        max-wait: -1ms #最大阻塞等待时间 默认-1ms无限制
        max-idle: 20 #最大空闲连接数
        min-idle: 10 #最小空闲连接数
  session:
    store-type: redis  #REDIS,MONGODB,JDBC,HAZELCAST,NONE;
    redis:
      flush-mode: on_save
      namespace: spring:session
